export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const REQUEST_TOKEN_VERIFICATION = 'REQUEST_TOKEN_VERIFICATION'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
